PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT ?label ?lat ?long
WHERE {
  ?point rdfs:label ?label ;
    geo:lat ?lat ;
    geo:long ?long .
}