PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX : <https://www.nico-assfalg.de/semantic-web/kit-campus.ttl#>

SELECT ?kitname ?latitude ?longitude
FROM <https://www.nico-assfalg.de/semantic-web/kit-campus.ttl>
WHERE {
    ?k rdfs:label ?kitname ;
	    geo:lat ?latitude ;
        geo:long ?longitude .
}